name: Build and Deploy Node.js To-Do List to Docker Hub

on:
  push:
    branches:
      - node

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Clonons le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construisons l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-todolist:latest .

      # Étape 4 : Poussons l'image sur Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-todolist:latest
